# Generated by Django 5.0.2 on 2024-02-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_catagory_description_catagory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='image',
        ),
    ]
